### ISSUE TITLE
E/Capacitor/BlobWriter: failed to move file into place

### ISSUE THREAD

**Issue by djflip2016** [diachedelic/capacitor-blob-writer#21] opened 2020-08-19 15:35 UTC
any ideas as to why i would get this error here is a code snippet:
and yes the directory exists
    const res = await fetch('https://cdn.vox-cdn.com/thumbor/Ous3VQj1sn4tvb3H13rIu8eGoZs=/0x0:2012x1341/1400x788/filters:focal(0x0:2012x1341):format(jpeg)/cdn.vox-cdn.com/uploads/chorus_image/image/47070706/google2.0.0.jpg');
    const blob = await res.blob();

    const { uri } = await writeFile({
      path: 'workbay',
      directory: FilesystemDirectory.Documents,

      // data must be a Blob (creating a Blob which wraps other data types
      // is trivial)
      data: blob,

      // create intermediate directories if they don't already exist
      // default: false
      recursive: true,

      // fallback to Filesystem.writeFile instead of throwing an error
      // (you may also specify a unary callback, which takes an Error and returns
      // a boolean)
      // default: true
    });
  }

**Comment by diachedelic** [comment] 2020-08-20 03:10
Looks like this may be a duplicate of #19 - does your write succeed if you use `Filesystem.writeFile` instead of this plugin?

**Comment by djflip2016** [comment] 2020-08-20 15:45
yes im not getting nay errors do you happen to know where i could possibly view this file on the android emulator because it isnt showing any fails with the .data extension but how would i view that directory?

**Closed** 2020-12-10 23:13 UTC
