### ISSUE TITLE
Support for larger files

### ISSUE THREAD

**Issue by crabbydavis** [diachedelic/capacitor-blob-writer#61] opened 2023-05-04 15:23 UTC
First, thanks for the plugin! I'm using this to download and then write a sqlite DB to memory. My initial DB size is 320MB and the plugin isn't able to write a file that size (at least on iOS on an iPhone 12 mini). The largest file I've been able to write so far is 270MB. The plugin was able to write the 320MB file on my laptop on the iOS simulator.

The plugin tries to use the fallback mode, but that also fails. It ends up creating the file but doesn't write any data into it.

The error I get is for the 320MB file is, "WebKit encountered an internal error."

Thanks for taking a look at this!

![Screenshot 2023-05-04 at 9 05 11 AM](https://user-images.githubusercontent.com/15008042/236251107-8c58e81b-8793-43e9-9fd9-732db6436a80.png)

**Comment by diachedelic** [comment] 2023-05-05 02:11
Duplicate of #22. Do you have time to implement the append feature (#11), a prerequisite for what you're asking?

**Closed by diachedelic** 2023-05-05 02:11 UTC

**Comment by Miguelmcanabal** [comment] 2023-05-29 18:05
Any news on this? Im facing the same issue.

**Comment by crabbydavis** [comment] 2023-05-30 16:58
@Miguelmcanabal I ended up just using the @capacitor/filesystem plugin. There's an appendFile method so that you can write the file in chunks. If you fetch your file as an array buffer, you can loop through it, grab slices, and write those slices using appendFile. I don't have timings to provide, but it writes quickly.

**Comment by AgustinBaffo** [comment] 2024-10-15 00:05
I was able to wrote huge file (>5GB) using [capacitor-file-chunk package](https://www.npmjs.com/package/capacitor-file-chunk?activeTab=readme#2-start-the-server). They implemented the append feature over this repo:

> This plugin builds on the original concept and code of the [Capacitor Blob Writer](https://github.com/diachedelic/capacitor-blob-writer) plugin by providing the ability to read and write files in chunks, offering improved performance compared to the Capacitor Filesystem plugin. It enables direct communication and exchange of binary data with a localhost web server, eliminating the need for base64 conversion.
